-- ==============================================================================
-- DATABASE SCHEMA: QUẢN LÝ THU CHI CÁ NHÂN & SAO KÊ GIAO DỊCH
-- Chạy đoạn script này trong Supabase Dashboard -> SQL Editor
-- ==============================================================================

-- 1. Tạo bảng danh mục (categories)
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    color VARCHAR(30) DEFAULT '#10b981',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Tạo bảng giao dịch sao kê (transactions)
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(15, 2) NOT NULL,
    type VARCHAR(10) NOT NULL CHECK (type IN ('IN', 'OUT')),
    content TEXT NOT NULL,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Bật Row Level Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- 4. Tạo Policy cho phép CRUD (phù hợp cho web app cá nhân & demo)
CREATE POLICY "Public read categories" ON public.categories FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public insert categories" ON public.categories FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Public update categories" ON public.categories FOR UPDATE TO anon, authenticated USING (true);

CREATE POLICY "Public read transactions" ON public.transactions FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public insert transactions" ON public.transactions FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Public update transactions" ON public.transactions FOR UPDATE TO anon, authenticated USING (true);
CREATE POLICY "Public delete transactions" ON public.transactions FOR DELETE TO anon, authenticated USING (true);

-- 5. Thêm dữ liệu danh mục mẫu
INSERT INTO public.categories (name, color) VALUES
('Ăn uống & Cà phê', '#f59e0b'),
('Lương & Thưởng', '#10b981'),
('Hóa đơn & Tiện ích', '#8b5cf6'),
('Di chuyển & Xăng xe', '#3b82f6'),
('Mua sắm & Gia dụng', '#ec4899'),
('Đầu tư & Tiết kiệm', '#06b6d4'),
('Chưa phân loại', '#64748b')
ON CONFLICT DO NOTHING;

-- 6. Thêm dữ liệu giao dịch mẫu (type IN = Tiền vào, type OUT = Tiền ra)
INSERT INTO public.transactions (amount, type, content, category_id, note, created_at)
VALUES 
(25000000, 'IN', 'CTY ABC CHUYEN LUONG THANG 09/2026', 2, 'Lương chính thức', NOW() - INTERVAL '1 day'),
(45000, 'OUT', 'HIGHLANDS COFFEE - QR MBBANK 0987654321', 1, 'Cà phê sáng', NOW() - INTERVAL '5 hours'),
(1500000, 'OUT', 'EVN HANOI TIEN DIEN KY 08/2026', 3, 'Tiền điện sinh hoạt gia đình', NOW() - INTERVAL '2 days'),
(75000, 'OUT', 'BE GROUP - CUOC XE 4 CHO TU NHA DEN CONG TY', 4, 'Đi làm trời mưa', NOW() - INTERVAL '1 day'),
(3000000, 'IN', 'NGUYEN VAN B CHUYEN TIEN DUA ANH FREELANCE', 2, 'Dự án sao kê tự động', NOW() - INTERVAL '3 days');

-- 7. Bảng công việc & nhắc nhở tài chính (TickTick Task Planner)
CREATE TABLE IF NOT EXISTS public.tasks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    amount NUMERIC(15, 2) DEFAULT 0,
    due_date DATE NOT NULL,
    priority VARCHAR(10) DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low', 'none')),
    is_completed BOOLEAN DEFAULT FALSE,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read tasks" ON public.tasks FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public insert tasks" ON public.tasks FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Public update tasks" ON public.tasks FOR UPDATE TO anon, authenticated USING (true);
CREATE POLICY "Public delete tasks" ON public.tasks FOR DELETE TO anon, authenticated USING (true);
